### ISSUE TITLE
Milestone 4: Add more anlaysis

### ISSUE THREAD

**Issue by dorisyycai** [UBC-MDS/RaincouverPrediction#87]
feedback:
Maybe include why you chose f1 score as the matrix or what does f1 score represents? In Fig 5, you included the values for recall, precision, and support but did not mention any of them in your report except for f1-score which makes the respective columns redundant in my opinion.

After hyperparameter optimization, precision, recall, f1 score, and support were mentioned, they weren't displayed while selecting the model based on the f1 score. Consider including a matrix or list of these scoring metrics before finalizing the choice based on the f1 score.

Modelling: Are we considering each observation from one day to be independent to other days? As you are using a time series data, did you make any assumptions on why you were able to conclude that the observations are independent of another? Brief explanations on your approach to the models might be helpful since weather forecasting is usually dependent on past values. Otherwise, you can't predict whether it will be raining on a particular day or not since your evaporation data is already dependent on the rain that happened on the day.

Accuracy Metrics: Why was f1 score used as your accuracy metric? Have you considered using any other scores?

In the discussion section you mentioned that feature engineering can be helpful in the future. What kind of feature engineering would you suggest from your data?

**Comment by sivakornchong** [comment]
Ok, we can explain further on why F1 score was used.
We will elaborate more on why we have the table, and we use recall/ precision to explain more. 

IID assumption is difficult with temporal data. We may add a remark on that, but still proceed with our analysis. Evaporation data is not dependent on the rain. 

Add a section on future and move the content of the report around.
