### ISSUE TITLE
Milestone 4: Folder structure

### ISSUE THREAD

**Issue by dorisyycai** [UBC-MDS/RaincouverPrediction#88]
feedback:
You included an environment file in your root repo but there is no instruction for how to use it, so I would suggest you to move it to maybe archive folder (?) as the dependencies included in the environment file seems to exclude click, jupyter-book and so on. 

There are similar files for different milestones in notebooks and reports folder. I'm uncertain which one to select for review. Would it be possible to tidy up the structure by removing any unnecessary or redundant files?

FIX: Is the notebooks directory required? The report will be rendered by the jupyter book in reports, so perhaps this folder can be removed?

**Comment by sivakornchong** [comment]
Rename all the other notebooks from milestones to archive

**Comment by wqxxzd** [comment]
Move the environment file inside the archive
