### ISSUE TITLE
Milestone 4: Add docstring to scripts

### ISSUE THREAD

**Issue by dorisyycai** [UBC-MDS/RaincouverPrediction#92]
feedback:
 A full docstring (examples, input data types, etc.) might help users to understand how to use the scripts more clearly. This is relevant for the classification.py, drop_split_preprocess.py, and eda.py scripts.

**Comment by wqxxzd** [comment]
Linked to this branch [https://github.com/UBC-MDS/RaincouverPrediction/tree/fix/add_docstring](url)

**Comment by wqxxzd** [comment]
Added in #100
