### ISSUE TITLE
Milestone 4 : Others

### ISSUE THREAD

**Issue by dorisyycai** [UBC-MDS/RaincouverPrediction#93]
feedback:
This project uses the MIT license which protects code only. A Creative Commons license should be used as well to cover the report / writing section of the repo

It is not clear who to reach out to in the case that users have questions or need help. It doesn’t seem like Tiffany has this listed in her example repo either, but perhaps you could list a contact within the Readme of contributing file.

Your code_of_conduct.md references Tiffany’s email for issues. This should be changed to one of the project team members.

**Comment by wqxxzd** [comment]
License is included in RaincouverPrediction #90

**Comment by sivakornchong** [comment]
code_of_conduct makes sense to have Tiff's email. 
We editted the Contributing.md to accomodate names of the founding members.
